config/routes.rb
Rails.application.routes.draw do
  
  resources :categories
  resources :articles do
    resources :comments, only: [:create, :update, :destroy]
  end
  
  devise_for :users

  root 'welcome#index'

  get '/contact', to: 'contact#info', as: 'contact' # el "as" es para darle un nombre a nuestra     ruta es decir
  #que desde el "get" hasta antes del "as" es nuestra ruta y es llamada con el apodo "contact" 
  # que se lo damos con el "as" y ese apodo es el que usamos con el _path

  #get '/contact' => 'contact#info'#Aca lo que hacemos es que la accion o metodo 
  # que es "/contact", busca cual es la ruta con el controlador y la vista que la van a ejecutar    esto es lo 
  # mismo que colocar el "to" en ves el "=>"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:update, :destroy]
  before_action :set_article
  before_action :authenticate_user!

  # POST /comments
  # POST /comments.json
  def create
    @comment = current_user.comments.new(comment_params)
    @comment.article = @article

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.article, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment.article}
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment.article, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @article, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  
    def set_article
      @article = Article.find(params[:article_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :article_id, :body)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<article>
   <header class="text-right be-small">
      <%= time_ago_in_words(comment.created_at) %> - 
       <%= link_to "Borrar", [@article,comment], class: "red" %>
   </header>
   <div class="row">
     <div class="col-xs-11 col-md-10 config-comment">
        <div class="box">
           <%= comment.body %>
        </div>
     </div>
  </div>
</article> 

app/views/comments/_form.html.erb
<%= form_with(model: [@article, @comment], remote: true, html: { id: "comments-form", :"data-type" => "json"}) do |form| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :comment_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Article:</strong>
  <%= @comment.article %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>