config/routes.rb
Rails.application.routes.draw do
  
  resources :categories
  resources :articles do
    resources :comments, only: [:create, :update, :destroy]
  end
  
  devise_for :users

  root 'welcome#index'

  get '/contact', to: 'contact#info', as: 'contact' # el "as" es para darle un nombre a nuestra     ruta es decir
  #que desde el "get" hasta antes del "as" es nuestra ruta y es llamada con el apodo "contact" 
  # que se lo damos con el "as" y ese apodo es el que usamos con el _path

  #get '/contact' => 'contact#info'#Aca lo que hacemos es que la accion o metodo 
  # que es "/contact", busca cual es la ruta con el controlador y la vista que la van a ejecutar    esto es lo 
  # mismo que colocar el "to" en ves el "=>"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/_navigation.html.erb
<header>
    <nav class="be-red white large-padding">
        <ul class="no-list row center-xs middle-xs">
            <li class=”col-md”>
                <h1 class=”no-margin” id=”logo”><%= link_to "AndTechBlog", root_path %></h1>
            </li>
            
            <li class="col-md">
                <%= link_to "Articulos", articles_path %>
            </li>

            <% @categories.each do |category| %>
                <li class="col-md">
                    <%= link_to category.name, category %>
                </li>
            <% end %>

            <li class="col-md">
                <%= link_to "Contacto", contact_path, style:"color:white2
                "%>
            </li>

            <% if user_signed_in? %>
                <li class="col-md">
                <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete, class:"session-conf" %>
                </li>
            <% else %>
                <li class="col-md">
                    <%= link_to "Iniciar sesión", new_user_session_path, class:"session-conf" %>
                </li>

                <li class="col-md">
                    <%= link_to "Crear cuenta", new_user_registration_path, class:"session-conf"  %>
                </li>
            <% end %>

        </ul>
    </nav> 
</header>